# Generated by Django 2.2.5 on 2019-09-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ob_tems',
            options={'ordering': ['kod'], 'verbose_name': 'Тема обращения', 'verbose_name_plural': 'Темы обращений'},
        ),
        migrations.AlterModelOptions(
            name='ob_vopros',
            options={'ordering': ['kod'], 'verbose_name': 'Вопрос обращения', 'verbose_name_plural': 'Вопросы обращений'},
        ),
        migrations.AddField(
            model_name='ob_vopros',
            name='kod_tems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_panel.ob_tems', verbose_name='Наименование темы'),
        ),
        migrations.AlterField(
            model_name='ob_tems',
            name='kod',
            field=models.CharField(max_length=2, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='ob_tems',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='ob_vopros',
            name='kod',
            field=models.CharField(max_length=2, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='ob_vopros',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
