# Generated by Django 2.2.5 on 2019-09-30 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_panel', '0002_auto_20190927_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ob_vopros',
            name='kod',
            field=models.CharField(max_length=5, verbose_name='Код'),
        ),
        migrations.CreateModel(
            name='ob_list_tel_obr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kod_tems', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_panel.ob_tems', verbose_name='Наименование темы')),
                ('kod_vopros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_panel.ob_vopros', verbose_name='Наименование вопроса')),
            ],
            options={
                'verbose_name': 'Обращениe',
                'verbose_name_plural': 'Список обращений',
                'ordering': ['id'],
            },
        ),
    ]
