# Generated by Django 2.2.5 on 2019-09-30 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0003_auto_20190930_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ob_list_tel_obr',
            name='kod_tems',
        ),
        migrations.RemoveField(
            model_name='ob_list_tel_obr',
            name='kod_vopros',
        ),
        migrations.AddField(
            model_name='ob_list_tel_obr',
            name='vopros',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_panel.ob_vopros'),
        ),
        migrations.AlterField(
            model_name='ob_list_tel_obr',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
