# Generated by Django 2.2.5 on 2019-10-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='them_obr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vopros_obr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('kod_them', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base_obr.them_obr')),
            ],
        ),
    ]
