# Generated by Django 2.2.5 on 2019-10-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_obr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_obr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150)),
                ('kod_them', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base_obr.them_obr')),
                ('kod_vopr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base_obr.vopros_obr')),
            ],
        ),
    ]
