# Generated by Django 2.2.5 on 2019-10-01 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_obr', '0002_base_obr'),
    ]

    operations = [
        migrations.CreateModel(
            name='vid_obr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='base_obr',
            name='kod_vopr',
        ),
        migrations.AlterField(
            model_name='them_obr',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='vopros_obr',
        ),
        migrations.AddField(
            model_name='base_obr',
            name='kod_vid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base_obr.vid_obr'),
        ),
    ]
