# Generated by Django 2.2.5 on 2019-10-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_obr', '0003_auto_20191001_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='them_obr',
            name='kod',
            field=models.CharField(max_length=5),
        ),
    ]
