# Generated by Django 2.2.5 on 2019-10-01 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_obr', '0004_auto_20191001_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='vid_kons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='base_obr',
            name='kod_vid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base_obr.vid_kons'),
        ),
        migrations.DeleteModel(
            name='vid_obr',
        ),
    ]
