# Generated by Django 2.2.5 on 2019-10-01 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_obr', '0005_auto_20191001_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='rez_kons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='base_obr',
            name='kod_rez',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base_obr.rez_kons'),
        ),
    ]
