# Generated by Django 2.2.5 on 2019-10-03 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_obr', '0010_thema_obr'),
    ]

    operations = [
        migrations.AddField(
            model_name='them_obr',
            name='kod_thema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base_obr.thema_obr'),
        ),
    ]
