# Generated by Django 2.2.5 on 2019-10-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_obr', '0012_auto_20191003_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_obr',
            name='date_obr',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='base_obr',
            name='fio_oper',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='base_obr',
            name='kol_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='base_obr',
            name='snils',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='base_obr',
            name='fio',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
