# Generated by Django 2.2.5 on 2019-10-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_obr', '0013_auto_20191004_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_obr',
            name='kod_word',
            field=models.BooleanField(null=True),
        ),
    ]
